[Course]
Prefix = CS
Numbers = 1151 1411
First Assess Code = Q1a

# MUST BE AN INTEGER VALUE
Number of Modules = 14

# Dates MUST be in the form MM-DD, MM-D, M-DD, or M-D
Dates =
    5-14
    9-1

Exclude Dates =
    5-19
    7-9
    7-10
    7-11
    7-12
    7-13

# Time MUST be in form HH:MM PP, H:MM PP, HH:M PP, or H:M PP
Due Time = 5:00 PM

# Day of the week that quizzes and assignments are due
Quiz Due Day = Friday
Assignment Due Day = Wednesday

# The numbers of weeks after the due date–MUST BE INTEGER VALUES
Too Late Offset = 2
Resubmission Deadline Offset = 3

Base Path = ~/Private/grades

[Mail Merge]
# These are the Thunderbird Mail Merge addon column headers that get
# used in the email templates
Headers =
    Course
    FirstName
    LastName
    Email
    Date
    MidtermAlert
    NumberOfModulesBehind
    YouAreInModule
    YouShouldBeInModule
    NoWorkDone
    NothingLate
    NextQuizTooLate
    NextQuizTooLateDate
    NextAssignmentTooLate
    NextAssignmentTooLateDate
    NextAssignmentResubmit
    ResubmitDeadLine

# The format to use for dates–Percent signs must be escaped by using %%
Date Format = %%-I:%%M %%p on %%A %%-d %%B %%Y
