
[Course]
prefix = "CS"
numbers = [1151, 1411]
first_assess_code = "Q1a"
number_of_modules = 14

# Exact names or substrings in the Canvas export Name column to ignore
ignored_students = [
    "Points Possible",
    "Student, Test",
    "Test Student"
]

[Course.Dates]
# Dates MUST be in the form MM-DD, MM-D, M-DD, or M-D
# Term start and end dates, excluding finals week
dates = [
    "5-4",
    "9-1"
]
# Finals week start and end dates
final_dates = [
    "9-4",
    "9-8"
]
# Term dates that are normally class dates, where no class is held
exclude_dates = [
    "5-19",
    "7-9",
    "7-10",
    "7-11",
    "7-12",
    "7-13"
]

[Course.Assessments]
non_academic = [
    "Feedback Survey",
    "Introductory Quiz"
]
[Course.Assessments.Quizzes]
due_time = "5:00 PM"
due_day = "Friday"
# Days until too late to turn in
too_late_deadline_offset = 14
[Course.Assessments.Assignments]
due_time = "5:00 PM"
due_day = "Wednesday"
# Days until too late to turn in
too_late_deadline_offset = 14
# Days until too late to resubmit updated solution
resubmission_deadline_offset = 21
[Course.Assessments.Final]
due_time = "5:00 PM"
due_day = "Friday"

[System]
base_path = "~/Private/grades"
# Keywords used to identify the correct CSV files for a given date
grades_file_keyword = "Grades"
missing_file_keyword = "missingAssignments"
output_file_prefix = "status-"

# Assignment Code Extraction Settings
# Delimiter used to split the assignment title (use " " for any whitespace)
assignment_code_delimiter = " "
# The position of the assignment code after splitting (0-indexed; 1 = 2nd position)
assignment_code_index = 1


[Mail_Merge]
domain = "d.umn.edu"
headers = [
    "Course",
    "First Name",
    "Last Name",
    "Email",
    "As Of Date",
    "Midterm Alert",
    "Modules Behind",
    "Last Module",
    "Current Module",
    "No Work Done",
    "Nothing Late",
    "Quiz Late",
    "Quiz Late Date",
    "Assign Late",
    "Assign Late Date",
    "Resubmit",
    "Resubmit Date"
]
date_format = "%-I:%M %p on %A %-d %B %Y"
