import logging
from datetime import datetime, time
from courseStatus import AppConfig, Course


def test_course_initialize_dynamic_modules(app_config: AppConfig, caplog) -> None:
    """Tests that the Course structure accurately generates all
    dynamic assignments."""

    course = Course(app_config, 2026)

    # A WARNING is generated by module 9, which has a quiz due date
    # that falls on an excluded date.
    caplog.set_level(logging.WARNING)
    assert (
        "Shifted date '2026-07-02' for Quizzes falls on a globally excluded date."
        in caplog.text
    )

    modules = course.modules

    # Module 1 has Quizzes, Assignments, and Geditr
    assert 1 in modules
    assert modules[1].get_assessment("Quizzes") is not None
    assert modules[1].get_assessment("Assignments") is not None

    geditr1 = modules[1].get_assessment("Geditr")
    assert geditr1 is not None
    assert geditr1.due_date.time() == time(2, 0)
    assert geditr1.due_date.weekday() == 5  # Saturday

    # Module 13 only has Geditr
    assert 13 in modules
    assert modules[13].get_assessment("Quizzes") is None
    assert modules[13].get_assessment("Assignments") is None
    assert modules[13].get_assessment("Geditr") is not None

    # Finals Week
    assert "f" in modules
    final_quiz = modules["f"].get_assessment("Quizzes")
    final_geditr = modules["f"].get_assessment("Geditr")

    assert final_quiz is not None
    assert final_quiz.is_final is True

    assert final_geditr is not None
    assert final_geditr.due_date.time() == time(4, 0)
    assert final_geditr.due_date.weekday() == 1  # Tuesday


# Test relative day offsets:


def test_positive_days_verbose(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    base = datetime(2026, 10, 1)
    result = course._apply_rule(base, "+3 days")
    assert result == datetime(2026, 10, 4)


def test_negative_days_shorthand(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    base = datetime(2026, 10, 5)
    result = course._apply_rule(base, "-1d")
    assert result == datetime(2026, 10, 4)


def test_implicit_days(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    base = datetime(2026, 10, 10)
    result = course._apply_rule(base, "+2")
    assert result == datetime(2026, 10, 12)


# Testing relative weekdays and synonyms


def test_next_weekday(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    # Base: Wednesday, Oct 7, 2026
    base = datetime(2026, 10, 7)
    # Next Monday should be Oct 12, 2026
    result = course._apply_rule(base, "next Monday")
    assert result == datetime(2026, 10, 12)


def test_last_weekday_shorthand(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    # Base: Wednesday, Oct 7, 2026
    base = datetime(2026, 10, 7)
    # Last Friday should be Oct 2, 2026
    result = course._apply_rule(base, "last fri")
    assert result == datetime(2026, 10, 2)


def test_this_weekday(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    # Base: Monday, Oct 5, 2026
    base = datetime(2026, 10, 5)
    # This Thursday should be Oct 8, 2026
    result = course._apply_rule(base, "this tu")
    assert result == datetime(2026, 10, 6)


def test_synonym_following(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    base = datetime(2026, 10, 7)  # Wednesday
    result = course._apply_rule(base, "following Monday")
    assert result == course._apply_rule(base, "next Monday")


def test_synonym_previous(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    base = datetime(2026, 10, 7)  # Wednesday
    result = course._apply_rule(base, "previous friday")
    assert result == course._apply_rule(base, "last fri")


# Testing year-wrapping boundary cases


def test_offset_wraps_to_new_year(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    base = datetime(2026, 12, 30)
    # +3 days from Dec 30, 2026 -> Jan 2, 2027
    result = course._apply_rule(base, "+3 days")
    assert result == datetime(2027, 1, 2)


def test_next_weekday_wraps_to_new_year(app_config: AppConfig, caplog) -> None:
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    # Base: Thursday, Dec 31, 2026
    base = datetime(2026, 12, 31)
    # Next Tuesday should cross into 2027 -> Jan 5, 2027
    result = course._apply_rule(base, "next Tuesday")
    assert result == datetime(2027, 1, 5)


# Test dates in first 10 modules in app_config


def test_module_1_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 1 dates correspond to the week of May 4-8, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod1 = course.get_module(1)
    assert mod1 is not None

    quiz = mod1.get_assessment("Quizzes")
    assign = mod1.get_assessment("Assignments")

    assert quiz is not None
    assert quiz.due_date == datetime(2026, 5, 11, 17, 0)

    assert assign is not None
    assert assign.due_date == datetime(2026, 5, 6, 17, 0)


def test_module_2_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 2 dates correspond to the week of May 11-15, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod2 = course.get_module(2)
    assert mod2 is not None

    quiz = mod2.get_assessment("Quizzes")
    assign = mod2.get_assessment("Assignments")

    assert quiz is not None
    assert quiz.due_date == datetime(2026, 5, 14, 17, 0)

    assert assign is not None
    assert assign.due_date == datetime(2026, 5, 13, 17, 0)


def test_module_3_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 3 dates correspond to the week of May 18-22, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod3 = course.get_module(3)
    assert mod3 is not None

    quiz = mod3.get_assessment("Quizzes")
    assign = mod3.get_assessment("Assignments")

    assert quiz is not None
    assert quiz.due_date == datetime(2026, 5, 25, 17, 0)

    assert assign is None


def test_module_4_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 4 dates correspond to the week of May 25-29, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod4 = course.get_module(4)
    assert mod4 is not None

    quiz = mod4.get_assessment("Quizzes")
    assign = mod4.get_assessment("Assignments")

    assert quiz is not None
    assert quiz.due_date == datetime(2026, 5, 27, 17, 0)

    assert assign is None


def test_module_5_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 5 dates correspond to the week of June 1-5, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod5 = course.get_module(5)
    assert mod5 is not None

    quiz = mod5.get_assessment("Quizzes")
    assign = mod5.get_assessment("Assignments")

    assert quiz is not None
    assert quiz.due_date == datetime(2026, 6, 9, 17, 0)

    assert assign is not None
    assert assign.due_date == datetime(2026, 6, 3, 17, 0)


def test_module_6_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 6 dates correspond to the week of June 8-12, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod6 = course.get_module(6)
    assert mod6 is not None

    quiz = mod6.get_assessment("Quizzes")
    assign = mod6.get_assessment("Assignments")

    assert quiz is not None
    assert quiz.due_date == datetime(2026, 6, 15, 17, 0)

    assert assign is not None
    assert assign.due_date == datetime(2026, 6, 10, 17, 0)


def test_module_7_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 7 dates correspond to the week of June 15-19, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod7 = course.get_module(7)
    assert mod7 is not None

    quiz = mod7.get_assessment("Quizzes")
    assign = mod7.get_assessment("Assignments")

    assert quiz is not None
    assert quiz.due_date == datetime(2026, 6, 18, 17, 0)

    assert assign is not None
    assert assign.due_date == datetime(2026, 6, 17, 17, 0)


def test_module_8_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 8 dates correspond to the week of June 22-26, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod8 = course.get_module(8)
    assert mod8 is not None

    quiz = mod8.get_assessment("Quizzes")
    assign = mod8.get_assessment("Assignments")

    assert quiz is not None
    assert quiz.due_date == datetime(2026, 6, 29, 17, 0)

    assert assign is None


def test_module_9_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 9 dates correspond to the week of June
    29-July 3, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod9 = course.get_module(9)
    assert mod9 is not None

    quiz = mod9.get_assessment("Quizzes")
    assign = mod9.get_assessment("Assignments")

    assert quiz is not None
    # This will generate a warning as 7-2 is an exclude date
    assert quiz.due_date == datetime(2026, 7, 2, 17, 0)

    assert assign is None


def test_module_10_dates_and_assessments(app_config: AppConfig, caplog) -> None:
    """Verifies that Module 10 dates correspond to the week of July 6-10, 2026."""
    course = Course(app_config, 2026)

    caplog.set_level(logging.WARNING)
    assert "Shifted date" in caplog.text

    mod10 = course.get_module(10)
    assert mod10 is not None

    quiz = mod10.get_assessment("Quizzes")
    assign = mod10.get_assessment("Assignments")

    assert quiz is not None
    assert quiz.due_date == datetime(2026, 7, 17, 17, 0)

    assert assign is None
